import 'dotenv/config'; import express from 'express'; import cors from 'cors'; import morgan from 'morgan'; import mongoose from 'mongoose'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import multer from 'multer'; import path from 'path'; import fs from 'fs'; import {fileURLToPath} from 'url';
import {User,Category,Product,Project,Testimonial,Setting} from './models.js'; import {auth} from './auth.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url)); const app=express(); const PORT=process.env.PORT||5000;
await mongoose.connect(process.env.MONGO_URI||'mongodb://127.0.0.1:27017/singhaniya_decor');
app.use(cors({origin:true,credentials:true})); app.use(express.json({limit:'2mb'})); app.use(morgan('dev'));
const uploads=path.join(__dirname,'../uploads'); fs.mkdirSync(uploads,{recursive:true}); app.use('/uploads',express.static(uploads));
const storage=multer.diskStorage({destination:(_,__,cb)=>cb(null,uploads),filename:(_,f,cb)=>cb(null,Date.now()+'-'+f.originalname.replace(/[^a-zA-Z0-9._-]/g,'-'))}); const upload=multer({storage,limits:{fileSize:8*1024*1024}});
const slug=s=>(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
app.get('/api/health',(_,r)=>r.json({ok:true}));
app.post('/api/auth/login',async(req,res)=>{const u=await User.findOne({email:req.body.email}); if(!u||!await bcrypt.compare(req.body.password||'',u.password))return res.status(401).json({message:'Invalid credentials'});res.json({token:jwt.sign({id:u._id,email:u.email,role:u.role},process.env.JWT_SECRET,{expiresIn:'7d'}),user:{email:u.email,role:u.role}})});
app.post('/api/upload',auth,upload.single('image'),(req,res)=>res.json({url:'/uploads/'+req.file.filename}));
const defs=[['categories',Category],['products',Product],['projects',Project],['testimonials',Testimonial]];
for(const [route,M] of defs){app.get('/api/'+route,async(req,res)=>{let q={}; if(route==='products'){if(req.query.category)q.category=req.query.category;if(req.query.search)q.name={$regex:req.query.search,$options:'i'};q.active={$ne:false}} if(route==='testimonials')q.active={$ne:false};res.json(await M.find(q).sort(route==='categories'?{order:1}:{createdAt:-1}))}); app.get('/api/'+route+'/:id',async(req,res)=>{const doc=await M.findOne({$or:[{_id:mongoose.isValidObjectId(req.params.id)?req.params.id:null},{slug:req.params.id}]});if(!doc)return res.status(404).json({message:'Not found'});res.json(doc)}); app.post('/api/'+route,auth,async(req,res)=>{let b={...req.body};if((route==='products'||route==='categories')&&!b.slug)b.slug=slug(b.name);res.status(201).json(await M.create(b))}); app.put('/api/'+route+'/:id',auth,async(req,res)=>{let b={...req.body};if((route==='products'||route==='categories')&&!b.slug)b.slug=slug(b.name);res.json(await M.findByIdAndUpdate(req.params.id,b,{new:true,runValidators:true}))}); app.delete('/api/'+route+'/:id',auth,async(req,res)=>{await M.findByIdAndDelete(req.params.id);res.json({ok:true})});}
app.get('/api/settings',async(_,res)=>{const rows=await Setting.find();res.json(Object.fromEntries(rows.map(x=>[x.key,x.value])))});app.put('/api/settings',auth,async(req,res)=>{for(const [key,value] of Object.entries(req.body))await Setting.findOneAndUpdate({key},{value},{upsert:true,new:true});res.json({ok:true})});
const dist=path.join(__dirname,'../../client/dist'); if(fs.existsSync(dist)){app.use(express.static(dist));app.get('*',(req,res)=>res.sendFile(path.join(dist,'index.html')))}
app.use((e,_,res,__)=>{console.error(e);res.status(500).json({message:e.message||'Server error'})}); app.listen(PORT,()=>console.log('API on http://localhost:'+PORT));
